### ISSUE TITLE
discovery should have some default for formats argument

### ISSUE THREAD

**Issue by mpo-vliz** [vliz-be-opsci/py-sema#75]
get_graph_for_formats of course as a name makes the dependency required

but an alternative could be made that defaults to some (formats) that are to be fetched when the user did not specifiy a preference

**Comment by marc-portier** [comment]
since https://github.com/vliz-be-opsci/py-sema/pull/76/commits/d6b1926a844bb11f5435036fc891e19be92f3112#diff-80d91b0cc1df1715d9d207e3ff94f793e3b0494906423e250d41c4d5ae876df1R185-R213 this is effectively no longer needed

this implementation now will fallback to all known rdf-mime-types in the chain of strategies to effectively get structured content for the subject-uri 'by default'

the passed mime-types now only ensure those all get called prior to that

closure should follow up after merge of #76

**Comment by marc-portier** [comment]
#76 merged
